# 2 ----Moviing window to get the averages 

In [186]:
import numpy as np
def moving_avg(arr):
    n1=0
    n2=1
    n3=2
    avg=np.zeros(mov_avg_val)
    for x in range(0,mov_avg_val):
        #print(n1,n2,n3)
        avg1=(arr1[n1]+arr1[n2]+arr1[n3])/3
        print(arr1[n1],arr1[n2],arr1[n3])
        if x<=mov_avg_val:
            n1=n1+1
            n2=n2+1
            n3=n3+1
        avg[x]=avg1
    print(avg)
        
    
arr1=np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
win=3
mov_avg_val=len(arr1)-win+1
moving_avg(arr1)
#print(avg)

3 5 7
5 7 2
7 2 8
2 8 10
8 10 11
10 11 65
11 65 72
65 72 81
72 81 99
81 99 100
99 100 150
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


# 1----Give user input as True or False to sepecify Increasing/Decreasing respectively

In [175]:
def Van_array(arr):
    print('x')
    x=0
    #N=4
    for row in res_array:
        for i in range(1,N+1):
            row[i-1]=np.power(arr[x],i)
            #print(row[i])
        x=x+1
    print(res_array)  
    
def Van_array1(arr):
    #N=4
    x=0
    for row in res_array:
        for i in range(len(row)):
            row[i]=np.power(arr[x],N-i-1)
            #print(res_array[i])
        x=x+1
    print(res_array)
        

In [183]:
arr=np.array([1,2,3,4])
N=4
res_array=np.zeros((len(arr),N))
increasing=input("Please give True/False value for increasing")
print(increasing)
if increasing==True:
    Van_array(arr)
else:
    Van_array1(arr)

Please give True/False value for increasingFalse
False
[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


In [185]:
Van_array(arr)

x
[[  1.   1.   1.   1.]
 [  2.   4.   8.  16.]
 [  3.   9.  27.  81.]
 [  4.  16.  64. 256.]]
